trigger:
  branches:
    include:
      - main   # change if your branch is 'master'

pool:
  name: 'local-agent'   # use your self-hosted agent pool, or 'ubuntu-latest' for cloud agents

steps:
- script: python --version
  displayName: 'Check Python version'

- script: pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    set PYTHONPATH=%CD%
    pytest
  displayName: 'Run tests'

